### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KirisameVanilla** [Makstein/SnowbreakGachaExport#34]
- [ ] GachaHistoryImport: Import selected gacha pool
- [ ] ModManager: description?
- [ ] ModManager: Better UI
- [ ] README: Prettify README
